export const customers = [
  {
    id: 1,
    name: "Rajesh Kumar",
    title: `Rajesh Kumar is the Chief Executive Officer (CEO) of our company, overseeing the strategic direction and overall management. With a career spanning over 22 years, Rajesh has been instrumental in driving growth and innovation. His leadership has led to significant market expansions and operational improvements. Rajesh is known for his strategic acumen, strong decision-making skills, and ability to inspire teams. Under his guidance, the company has achieved several milestones, including launching new products and entering new markets. His vision for the future continues to shape the company's path and success.`,
    address: "1010 Main St, Delhi",
  },
  {
    id: 2,
    name: "Anita Desai",
    title: `Anita Desai is the Chief Technology Officer (CTO) at our firm, responsible for leading technological advancements and innovation. With 18 years of experience in tech leadership, Anita has spearheaded numerous successful projects and technology upgrades. She excels in identifying emerging technologies and integrating them into business strategies. Anita’s expertise in software development and IT infrastructure has been crucial in maintaining the company’s competitive edge. Her leadership ensures that the company remains at the forefront of technological innovation.`,
    address: "2020 Elm St, Mumbai",
  },
  {
    id: 3,
    name: "Amit Patel",
    title: `Amit Patel serves as the Chief Financial Officer (CFO), managing all financial activities and strategies. With over 15 years in finance, Amit oversees budgeting, forecasting, and financial analysis. His expertise in financial planning has been vital for the company's stability and growth. Amit’s role includes managing risk, ensuring regulatory compliance, and providing strategic financial insights. His leadership in financial management has strengthened the company's financial health and supported its expansion plans.`,
    address: "3030 Oak St, Bangalore",
  },
  {
    id: 4,
    name: "Pooja Sharma",
    title: `Pooja Sharma is the Chief Operating Officer (COO) of our organization, handling day-to-day operations and process optimization. With 20 years of experience, Pooja is skilled in streamlining operations and enhancing productivity. She manages various departments to ensure seamless coordination and efficiency. Her focus on improving operational workflows has led to significant cost savings and operational excellence. Pooja’s strategic approach to operations supports the company’s growth and efficiency goals.`,
    address: "4040 Pine St, Hyderabad",
  },
  {
    id: 5,
    name: "Ravi Mehta",
    title: `Ravi Mehta is the Chief Marketing Officer (CMO), leading the company’s marketing strategies and campaigns. With a background in brand management and over 17 years of experience, Ravi drives brand awareness and market presence. His expertise includes market research, digital marketing, and campaign management. Ravi’s leadership in marketing has successfully launched several high-impact campaigns and enhanced customer engagement. His innovative strategies have contributed to the company's strong market position.`,
    address: "5050 Cedar St, Pune",
  },
  {
    id: 6,
    name: "Sita Reddy",
    title: `Sita Reddy serves as the Head of Human Resources, managing recruitment, employee relations, and organizational development. With 16 years of HR experience, Sita excels in talent management and employee engagement. Her responsibilities include developing HR policies, managing performance reviews, and ensuring compliance with labor laws. Sita’s strategic approach to HR has improved employee satisfaction and retention, contributing to a positive workplace culture. Her leadership supports the company’s growth and employee development initiatives.`,
    address: "6060 Birch St, Chennai",
  },
  {
    id: 7,
    name: "Suresh Gupta",
    title: `Suresh Gupta is the Chief Risk Officer (CRO), responsible for identifying and mitigating potential risks. With over 14 years in risk management, Suresh develops strategies to manage financial, operational, and regulatory risks. His role includes conducting risk assessments, implementing risk mitigation plans, and ensuring compliance with industry standards. Suresh’s expertise in risk management safeguards the company’s assets and supports its long-term stability and success.`,
    address: "7070 Maple St, Kolkata",
  },
  {
    id: 8,
    name: "Neelam Agarwal",
    title: `Neelam Agarwal is the Director of Product Management, overseeing product development and strategy. With 19 years of experience, Neelam leads product innovation and ensures alignment with market needs. She manages product lifecycle from conception to launch, focusing on customer requirements and competitive analysis. Her strategic direction in product management has led to successful product launches and market growth. Neelam’s role is crucial in maintaining the company’s product leadership.`,
    address: "8080 Cherry St, Jaipur",
  },
  {
    id: 9,
    name: "Sunil Verma",
    title: `Sunil Verma is the Chief Information Officer (CIO), responsible for overseeing the company’s IT infrastructure and strategy. With 21 years of experience in IT management, Sunil ensures that the company’s technology supports its business objectives. His expertise includes managing IT projects, enhancing cybersecurity, and integrating new technologies. Sunil’s leadership in IT has been pivotal in maintaining the company’s technological edge and operational efficiency.`,
    address: "9090 Rose St, Ahmedabad",
  },
  {
    id: 10,
    name: "Maya Kapoor",
    title: `Maya Kapoor is the Senior Director of Customer Success, focusing on enhancing customer satisfaction and loyalty. With 15 years of experience in customer service, Maya develops strategies to improve customer experience and address issues. Her role includes managing customer support teams, analyzing feedback, and implementing service improvements. Maya’s leadership has significantly boosted customer retention and satisfaction, supporting the company’s customer-centric approach.`,
    address: "1011 Orchid St, Surat",
  },
  {
    id: 11,
    name: "Rohit Singh",
    title: `Rohit Singh is the Head of Business Development, responsible for driving growth and expanding market opportunities. With 18 years in business development, Rohit identifies new markets and develops strategic partnerships. His expertise includes market analysis, strategic planning, and client relations. Rohit’s efforts in business development have led to increased revenue and market share, contributing to the company’s overall growth strategy.`,
    address: "1112 Tulip St, Indore",
  },
  {
    id: 12,
    name: "Priya Patel",
    title: `Priya Patel is the Director of Finance, overseeing financial planning, analysis, and reporting. With 16 years of experience, Priya manages budgeting, forecasting, and financial performance analysis. Her role includes ensuring financial accuracy, compliance, and providing strategic financial insights. Priya’s expertise in finance supports the company’s strategic objectives and financial health. Her leadership has been essential in guiding the company’s financial decisions and growth.`,
    address: "1213 Marigold St, Chandigarh",
  },
  {
    id: 13,
    name: "Vikram Rao",
    title: `Vikram Rao serves as the Chief Operations Officer (COO), managing daily operations and process improvements. With 20 years in operations management, Vikram optimizes workflows and enhances operational efficiency. His role includes overseeing multiple departments, implementing process changes, and ensuring smooth operations. Vikram’s expertise in operations has led to significant improvements in productivity and cost management, supporting the company’s operational goals.`,
    address: "1314 Jasmine St, Bhopal",
  },
  {
    id: 14,
    name: "Kavita Agarwal",
    title: `Kavita Agarwal is the Chief Strategy Officer (CSO), responsible for developing and executing business strategies. With over 15 years of experience in strategic planning, Kavita identifies growth opportunities and aligns strategies with business goals. Her role includes conducting market analysis, developing strategic initiatives, and overseeing implementation. Kavita’s strategic leadership has been crucial in guiding the company’s growth and ensuring alignment with market trends.`,
    address: "1415 Peony St, Noida",
  },
  {
    id: 15,
    name: "Ramesh Joshi",
    title: `Ramesh Joshi is the Director of IT Operations, overseeing IT infrastructure and support services. With 17 years of experience, Ramesh manages IT operations, ensures system reliability, and implements technology upgrades. His responsibilities include maintaining IT systems, supporting end-users, and managing IT projects. Ramesh’s leadership in IT operations has been vital in maintaining the company’s technological capabilities and operational efficiency.`,
    address: "1516 Cedar St, Lucknow",
  },
  {
    id: 16,
    name: "Neeta Sharma",
    title: `Neeta Sharma is the Head of Corporate Communications, managing internal and external communications. With 18 years in communications, Neeta develops strategies for corporate messaging, media relations, and stakeholder engagement. Her role includes overseeing communication campaigns, managing public relations, and enhancing the company’s brand image. Neeta’s expertise in communications has strengthened the company’s reputation and stakeholder relationships.`,
    address: "1617 Birch St, Dehradun",
  },
  {
    id: 17,
    name: "Amitabh Singh",
    title: `Amitabh Singh is the Chief Legal Officer (CLO), responsible for managing legal affairs and ensuring regulatory compliance. With 22 years of experience in corporate law, Amitabh oversees legal risk management, contract negotiations, and litigation. His role includes providing legal guidance, handling legal disputes, and ensuring adherence to laws. Amitabh’s expertise in legal management has been crucial in protecting the company’s interests and maintaining compliance.`,
    address: "1718 Rose St, Gurgaon",
  },
  {
    id: 18,
    name: "Minal Rao",
    title: `Minal Rao is the Director of Customer Analytics, focusing on leveraging data to enhance customer experience. With 16 years in analytics, Minal manages data analysis, customer insights, and reporting. Her responsibilities include analyzing customer behavior, identifying trends, and providing actionable insights. Minal’s expertise in analytics has supported data-driven decision-making and improved customer satisfaction through targeted strategies.`,
    address: "1819 Tulip St, Faridabad",
  },
  {
    id: 19,
    name: "Deepak Patel",
    title: `Deepak Patel serves as the Senior Director of Sales, responsible for driving sales strategies and revenue growth. With 19 years of experience in sales management, Deepak develops and implements sales plans, manages sales teams, and oversees client relationships. His role includes analyzing sales performance, identifying growth opportunities, and achieving sales targets. Deepak’s leadership in sales has significantly contributed to the company’s revenue and market presence.`,
    address: "1920 Marigold St, Jaipur",
  },
  {
    id: 20,
    name: "Isha Gupta",
    title: `Isha Gupta is the Chief Product Officer (CPO), leading product development and strategy. With over 17 years in product management, Isha oversees the product lifecycle, from development to launch. Her role includes managing product teams, defining product roadmaps, and ensuring market fit. Isha’s expertise in product strategy has driven successful product launches and enhanced the company’s product portfolio. Her leadership ensures alignment with customer needs and market trends.`,
    address: "2021 Orchid St, Kanpur",
  },
  {
    id: 21,
    name: "Vikas Kumar",
    title: `Vikas Kumar is the Director of Supply Chain Management, overseeing supply chain operations and logistics. With 18 years of experience, Vikas manages procurement, inventory, and distribution. His responsibilities include optimizing supply chain processes, reducing costs, and ensuring timely delivery. Vikas’s expertise in supply chain management has improved efficiency and supported the company’s operational goals. His leadership has been crucial in maintaining a smooth supply chain and meeting customer demands.`,
    address: "2122 Lotus St, Varanasi",
  },
  {
    id: 22,
    name: "Ritika Sharma",
    title: `Ritika Sharma is the Senior Director of Customer Experience, focused on enhancing customer satisfaction and loyalty. With over 16 years in customer service and experience management, Ritika develops strategies to improve customer interactions and address feedback. Her role includes managing customer support teams, analyzing service metrics, and implementing improvements. Ritika’s expertise in customer experience has strengthened the company’s service quality and customer relationships.`,
    address: "2223 Tulip St, Amritsar",
  },
  {
    id: 23,
    name: "Manoj Mehta",
    title: `Manoj Mehta is the Senior Director of Technology Strategy, responsible for defining and executing technology strategies. With 19 years in technology and strategy, Manoj oversees IT projects, evaluates emerging technologies, and aligns them with business goals. His role includes managing technology initiatives and infrastructure. Manoj’s expertise in technology strategy has been vital in guiding the company’s technological direction and maintaining a competitive edge.`,
    address: "2324 Orchid St, Nagpur",
  },
  {
    id: 24,
    name: "Prachi Jain",
    title: `Prachi Jain is the Chief Legal Officer (CLO), overseeing legal matters and regulatory compliance. With over 17 years in corporate law, Prachi manages legal risks, drafts contracts, and provides legal guidance. Her role includes handling litigation and ensuring compliance with laws. Prachi’s expertise in legal management has protected the company’s interests and ensured adherence to legal standards. Her leadership in legal affairs supports the company’s ethical and regulatory commitments.`,
    address: "2425 Lotus St, Bhopal",
  },
  {
    id: 25,
    name: "Rajesh Yadav",
    title: `Rajesh Yadav serves as the Head of Strategic Partnerships, focusing on developing and managing alliances. With over 15 years in business development, Rajesh identifies potential partners, negotiates agreements, and manages relationships. His responsibilities include developing partnership strategies and coordinating with external partners. Rajesh’s expertise in partnerships has expanded the company’s network and driven growth through strategic alliances. His leadership in partnerships supports the company’s strategic objectives.`,
    address: "2526 Peony St, Jaipur",
  },
  {
    id: 26,
    name: "Suman Patel",
    title: `Suman Patel is the Senior Director of Customer Experience, responsible for enhancing the customer journey. With over 18 years in customer experience management, Suman develops strategies to improve customer satisfaction and manage feedback. Her role includes leading customer experience initiatives and collaborating with other departments. Suman’s expertise in experience management has driven customer-centric strategies and supported the company’s commitment to exceptional service.`,
    address: "2627 Lotus St, Patna",
  },
  {
    id: 27,
    name: "Neha Singh",
    title: `Neha Singh is the Chief Innovation Officer (CIO), leading innovation initiatives and driving product development. With 20 years of experience in innovation management, Neha oversees the development of new products and services. Her role includes identifying market trends, fostering creativity, and implementing innovative solutions. Neha’s expertise in innovation has led to the creation of cutting-edge products and maintained the company’s competitive edge.`,
    address: "2728 Rose St, Srinagar",
  },
  {
    id: 28,
    name: "Arjun Reddy",
    title: `Arjun Reddy is the Director of Quality Assurance, overseeing quality control and process improvement. With over 16 years in quality management, Arjun ensures that products meet high standards and customer expectations. His responsibilities include implementing quality assurance processes, managing audits, and addressing quality issues. Arjun’s expertise in quality management has improved product reliability and customer satisfaction. His leadership supports the company’s commitment to quality.`,
    address: "2829 Tulip St, Coimbatore",
  },
  {
    id: 29,
    name: "Aarti Sharma",
    title: `Aarti Sharma is the Chief Human Resources Officer (CHRO), responsible for managing HR functions and employee relations. With 19 years in HR management, Aarti develops and implements HR policies, manages recruitment, and oversees employee development. Her role includes improving employee engagement, handling conflict resolution, and ensuring compliance with labor laws. Aarti’s expertise in HR has enhanced workplace culture and supported the company’s growth.`,
    address: "2930 Marigold St, Bhubaneswar",
  },
  {
    id: 30,
    name: "Sandeep Gupta",
    title: `Sandeep Gupta is the Director of Business Intelligence, focusing on data analysis and reporting. With over 15 years in analytics, Sandeep manages data collection, analysis, and visualization. His role includes providing insights to support business decisions and improving data-driven strategies. Sandeep’s expertise in business intelligence has enhanced the company’s decision-making capabilities and strategic planning. His leadership in analytics supports the company’s data-driven approach.`,
    address: "3031 Orchid St, Surat",
  },
  {
    id: 31,
    name: "Kiran Patel",
    title: `Kiran Patel is the Chief Compliance Officer (CCO), overseeing regulatory compliance and risk management. With 17 years in compliance, Kiran ensures adherence to laws and regulations. Her responsibilities include managing compliance programs, conducting audits, and addressing regulatory issues. Kiran’s expertise in compliance has protected the company from legal risks and supported its commitment to ethical standards. Her leadership in compliance ensures the company’s regulatory adherence.`,
    address: "3132 Lotus St, Raipur",
  },
  {
    id: 32,
    name: "Meera Joshi",
    title: `Meera Joshi is the Director of Research and Development, leading R&D efforts for new products and innovations. With 18 years of experience, Meera manages R&D projects, oversees product development, and fosters innovation. Her role includes coordinating research activities, managing development teams, and ensuring alignment with market needs. Meera’s expertise in R&D has driven the creation of innovative products and supported the company’s growth.`,
    address: "3233 Cedar St, Jodhpur",
  },
  {
    id: 33,
    name: "Suresh Patel",
    title: `Suresh Patel is the Chief Financial Officer (CFO), managing financial operations and strategy. With 21 years in finance, Suresh oversees budgeting, financial analysis, and risk management. His role includes ensuring financial accuracy, managing investments, and providing strategic financial guidance. Suresh’s expertise in finance supports the company’s financial health and strategic objectives. His leadership has been vital in guiding the company’s financial planning and growth.`,
    address: "3334 Birch St, Agra",
  },
  {
    id: 34,
    name: "Rani Agarwal",
    title: `Rani Agarwal serves as the Director of Product Marketing, focusing on product positioning and market strategy. With over 16 years of experience, Rani develops marketing strategies, manages product launches, and conducts market research. Her role includes creating marketing campaigns and analyzing market trends. Rani’s expertise in product marketing has enhanced the company’s market presence and supported successful product launches. Her leadership drives effective marketing strategies.`,
    address: "3435 Marigold St, Mysore",
  },
  {
    id: 35,
    name: "Vivek Jain",
    title: `Vivek Jain is the Chief Technology Officer (CTO), responsible for technology strategy and innovation. With 20 years in tech leadership, Vivek oversees IT projects, manages technology infrastructure, and drives digital transformation. His role includes evaluating new technologies, improving systems, and ensuring alignment with business goals. Vivek’s expertise in technology management has been crucial in maintaining the company’s technological edge and operational efficiency.`,
    address: "3536 Rose St, Trivandrum",
  },
  {
    id: 36,
    name: "Ritika Sharma",
    title: `Ritika Sharma is the Senior Director of Customer Experience, managing customer service strategies and operations. With over 16 years in customer service management, Ritika enhances customer satisfaction through feedback analysis and service improvements. Her role includes leading customer support teams, implementing experience strategies, and driving customer-centric initiatives. Ritika’s leadership in customer experience supports the company’s commitment to exceptional service and customer loyalty.`,
    address: "3637 Tulip St, Varanasi",
  },
  {
    id: 37,
    name: "Pankaj Yadav",
    title: `Pankaj Yadav is the Chief Operating Officer (COO), overseeing daily operations and process improvements. With 18 years of experience, Pankaj manages operational workflows, enhances efficiency, and ensures smooth functioning of departments. His role includes implementing process changes, managing resources, and optimizing operations. Pankaj’s expertise in operations has led to improved productivity and cost management, supporting the company’s operational goals.`,
    address: "3738 Cedar St, Patna",
  },
  {
    id: 38,
    name: "Anjali Reddy",
    title: `Anjali Reddy is the Director of Strategic Initiatives, focusing on business growth and strategy implementation. With over 17 years in strategy and operations, Anjali manages strategic projects, develops growth strategies, and oversees execution. Her role includes analyzing market trends, identifying opportunities, and coordinating initiatives. Anjali’s expertise in strategic planning supports the company’s growth objectives and competitive positioning.`,
    address: "3839 Orchid St, Chandigarh",
  },
  {
    id: 39,
    name: "Rohit Kapoor",
    title: `Rohit Kapoor serves as the Director of Talent Acquisition, managing recruitment and talent management. With 16 years of experience, Rohit develops hiring strategies, manages recruitment processes, and oversees talent acquisition. His role includes identifying talent needs, conducting interviews, and ensuring a smooth hiring process. Rohit’s expertise in talent acquisition supports the company’s growth by attracting and retaining top talent.`,
    address: "3940 Lotus St, Lucknow",
  },
  {
    id: 40,
    name: "Swati Gupta",
    title: `Swati Gupta is the Chief Marketing Officer (CMO), leading marketing strategies and brand management. With 15 years in marketing, Swati develops and executes marketing campaigns, manages brand positioning, and drives customer engagement. Her role includes overseeing market research, digital marketing, and advertising. Swati’s leadership in marketing has strengthened the company’s brand and market presence through innovative strategies and successful campaigns.`,
    address: "4041 Marigold St, Bangalore",
  },
  {
    id: 41,
    name: "Kartik Patel",
    title: `Kartik Patel is the Director of Financial Planning, responsible for budgeting and financial analysis. With over 18 years in finance, Kartik manages financial planning processes, oversees forecasts, and ensures financial accuracy. His role includes analyzing financial data, developing financial models, and supporting strategic financial decisions. Kartik’s expertise in financial planning contributes to the company’s financial health and strategic growth.`,
    address: "4142 Cedar St, Surat",
  },
  {
    id: 42,
    name: "Rashmi Joshi",
    title: `Rashmi Joshi is the Head of Corporate Development, focusing on mergers, acquisitions, and partnerships. With 17 years in corporate strategy, Rashmi manages strategic initiatives, evaluates business opportunities, and oversees integration. Her role includes negotiating deals, conducting due diligence, and supporting corporate growth. Rashmi’s expertise in corporate development has driven the company’s expansion and strategic positioning.`,
    address: "4243 Orchid St, Nagpur",
  },
  {
    id: 43,
    name: "Vikram Yadav",
    title: `Vikram Yadav is the Senior Director of IT Operations, managing technology infrastructure and support. With 20 years of experience, Vikram oversees IT operations, manages system reliability, and implements technology upgrades. His role includes supporting IT projects, enhancing cybersecurity, and ensuring system performance. Vikram’s leadership in IT operations has been crucial in maintaining the company’s technological capabilities and operational efficiency.`,
    address: "4344 Rose St, Coimbatore",
  },
  {
    id: 44,
    name: "Aarti Verma",
    title: `Aarti Verma is the Director of Product Strategy, leading product planning and development. With 16 years of experience, Aarti manages product roadmaps, oversees development, and aligns products with market needs. Her role includes conducting market research, defining product features, and coordinating with development teams. Aarti’s expertise in product strategy has driven successful product launches and supported the company’s growth.`,
    address: "4445 Tulip St, Faridabad",
  },
  {
    id: 45,
    name: "Nitin Kumar",
    title: `Nitin Kumar serves as the Chief Risk Officer (CRO), managing risk assessments and mitigation strategies. With over 15 years in risk management, Nitin develops risk management frameworks, conducts risk analyses, and implements mitigation plans. His role includes ensuring regulatory compliance, managing risk exposure, and protecting company assets. Nitin’s expertise in risk management supports the company’s stability and long-term success.`,
    address: "4546 Lotus St, Gurgaon",
  },
  {
    id: 46,
    name: "Neha Patel",
    title: `Neha Patel is the Director of Data Science, focusing on data analysis and insights. With 18 years in data science, Neha manages data projects, develops analytical models, and provides strategic insights. Her role includes analyzing complex data sets, supporting decision-making, and implementing data-driven strategies. Neha’s expertise in data science has enhanced the company’s analytics capabilities and supported data-driven growth.`,
    address: "4647 Cedar St, Noida",
  },
  {
    id: 47,
    name: "Vikas Sharma",
    title: `Vikas Sharma is the Chief People Officer (CPO), managing HR functions and organizational development. With over 16 years in HR management, Vikas develops HR strategies, oversees talent management, and supports employee development. His role includes managing recruitment, performance reviews, and employee engagement. Vikas’s leadership in HR has improved workplace culture and supported the company’s growth and development.`,
    address: "4748 Marigold St, Indore",
  },
  {
    id: 48,
    name: "Maya Mehta",
    title: `Maya Mehta is the Director of Operations, focusing on improving operational efficiency and process optimization. With 19 years in operations management, Maya manages operational workflows, enhances productivity, and oversees process improvements. Her role includes implementing operational changes, managing resources, and ensuring smooth functioning of departments. Maya’s expertise in operations has led to significant improvements in efficiency and cost management.`,
    address: "4849 Rose St, Kanpur",
  },
  {
    id: 49,
    name: "Rajeev Gupta",
    title: `Rajeev Gupta is the Chief Strategy Officer (CSO), responsible for strategic planning and business growth. With 17 years in strategy management, Rajeev develops strategic initiatives, manages business growth projects, and oversees execution. His role includes analyzing market trends, identifying opportunities, and aligning strategies with business objectives. Rajeev’s expertise in strategy supports the company’s growth and competitive positioning.`,
    address: "4950 Tulip St, Varanasi",
  },
  {
    id: 50,
    name: "Shikha Sharma",
    title: `Shikha Sharma serves as the Director of Marketing Strategy, leading marketing initiatives and brand management. With over 16 years in marketing, Shikha develops marketing strategies, manages campaigns, and oversees brand positioning. Her role includes conducting market research, analyzing trends, and implementing marketing plans. Shikha’s expertise in marketing strategy has enhanced the company’s brand presence and market reach.`,
    address: "5051 Lotus St, Surat",
  },
  {
    id: 51,
    name: "Ashok Kumar",
    title: `Ashok Kumar is the Senior Director of Product Development, overseeing product innovation and lifecycle management. With 18 years of experience, Ashok manages product teams, coordinates development efforts, and ensures product alignment with market needs. His role includes defining product features, conducting market research, and leading product launches. Ashok’s expertise in product development supports the company’s innovation and growth objectives.`,
    address: "5152 Cedar St, Jaipur",
  },
  {
    id: 52,
    name: "Sonia Reddy",
    title: `Sonia Reddy is the Chief Financial Officer (CFO), responsible for managing the company’s financial operations and strategy. With 20 years in finance, Sonia oversees budgeting, forecasting, and financial analysis. Her role includes managing financial risks, ensuring compliance, and providing strategic financial guidance. Sonia’s expertise in finance supports the company’s financial health and strategic goals. Her leadership has been crucial in guiding financial planning and growth.`,
    address: "5253 Rose St, Bhopal",
  },
  {
    id: 53,
    name: "Ravi Sharma",
    title: `Ravi Sharma is the Director of Business Operations, managing day-to-day operations and process improvements. With over 17 years in operations management, Ravi oversees operational workflows, enhances efficiency, and implements process changes. His role includes managing resources, ensuring smooth operations, and optimizing processes. Ravi’s expertise in business operations has led to improved productivity and cost management.`,
    address: "5354 Tulip St, Amritsar",
  },
  {
    id: 54,
    name: "Meenal Agarwal",
    title: `Meenal Agarwal serves as the Director of IT Strategy, focusing on technology planning and implementation. With 16 years of experience, Meenal manages IT projects, oversees technology infrastructure, and ensures alignment with business objectives. Her role includes evaluating new technologies, implementing IT solutions, and supporting digital transformation. Meenal’s expertise in IT strategy has been crucial in maintaining the company’s technological capabilities and efficiency.`,
    address: "5455 Lotus St, Coimbatore",
  },
  {
    id: 55,
    name: "Amit Desai",
    title: `Amit Desai is the Chief Marketing Officer (CMO), responsible for driving marketing strategies and brand growth. With 19 years in marketing, Amit develops marketing plans, manages campaigns, and oversees brand positioning. His role includes conducting market research, analyzing consumer behavior, and implementing marketing initiatives. Amit’s expertise in marketing has enhanced the company’s brand presence and market reach. His leadership supports the company’s strategic marketing goals.`,
    address: "5556 Cedar St, Jaipur",
  },
  {
    id: 56,
    name: "Kiran Sharma",
    title: `Kiran Sharma is the Director of Customer Insights, focusing on understanding and analyzing customer behavior. With over 17 years in customer research, Kiran manages customer data, conducts analysis, and provides actionable insights. Her role includes developing strategies to enhance customer experience and satisfaction. Kiran’s expertise in customer insights supports the company’s customer-centric approach and service improvements.`,
    address: "5657 Rose St, Surat",
  },
  {
    id: 57,
    name: "Siddharth Patel",
    title: `Siddharth Patel serves as the Chief Product Officer (CPO), overseeing product strategy and development. With 18 years in product management, Siddharth leads product teams, defines product roadmaps, and ensures market alignment. His role includes managing product lifecycle, conducting market research, and driving innovation. Siddharth’s expertise in product strategy has been pivotal in launching successful products and enhancing the company’s product portfolio.`,
    address: "5758 Tulip St, Faridabad",
  },
  {
    id: 58,
    name: "Geeta Yadav",
    title: `Geeta Yadav is the Director of Corporate Communications, managing internal and external communications. With over 15 years in communications, Geeta oversees corporate messaging, public relations, and media relations. Her role includes developing communication strategies, managing press releases, and enhancing the company’s image. Geeta’s expertise in communications supports the company’s public relations and corporate branding efforts.`,
    address: "5859 Cedar St, Bhopal",
  },
  {
    id: 59,
    name: "Manoj Kumar",
    title: `Manoj Kumar is the Chief Risk Officer (CRO), responsible for risk management and mitigation. With 16 years of experience, Manoj develops risk assessment frameworks, manages risk exposure, and ensures compliance with regulations. His role includes implementing risk management strategies and protecting company assets. Manoj’s expertise in risk management supports the company’s stability and long-term success.`,
    address: "5960 Lotus St, Kanpur",
  },
  {
    id: 60,
    name: "Rani Gupta",
    title: `Rani Gupta is the Director of Employee Engagement, focusing on enhancing employee satisfaction and organizational culture. With over 17 years in HR management, Rani develops and implements engagement strategies, manages employee programs, and oversees internal communications. Her role includes improving workplace culture and supporting employee development. Rani’s expertise in employee engagement contributes to a positive work environment and supports the company’s HR goals.`,
    address: "6061 Marigold St, Chennai",
  },
  {
    id: 61,
    name: "Tanya Sharma",
    title: `Tanya Sharma is the Director of Operations, focusing on improving operational efficiency and process optimization. With 16 years in operations management, Tanya manages day-to-day operations, implements process changes, and enhances productivity. Her role includes overseeing operational workflows, managing resources, and ensuring smooth functioning of departments. Tanya’s expertise in operations supports the company’s goals for efficiency and cost management.`,
    address: "6162 Tulip St, Bhopal",
  },
  {
    id: 62,
    name: "Amit Sharma",
    title: `Amit Sharma is the Chief Executive Officer (CEO), leading the company’s strategic direction and overall operations. With over 22 years in leadership, Amit oversees all aspects of the company’s performance, including finance, operations, and strategic initiatives. His role includes setting goals, managing executive teams, and ensuring business growth. Amit’s leadership drives the company’s success and aligns operations with its vision and goals.`,
    address: "6263 Cedar St, Chennai",
  },
  {
    id: 63,
    name: "Rohini Patel",
    title: `Rohini Patel is the Director of IT Operations, responsible for managing IT infrastructure and support. With 17 years of experience, Rohini oversees IT systems, ensures system reliability, and supports technology projects. Her role includes managing technology upgrades, implementing IT solutions, and enhancing cybersecurity. Rohini’s expertise in IT operations supports the company’s technological capabilities and operational efficiency.`,
    address: "6364 Lotus St, Surat",
  },
  {
    id: 64,
    name: "Neeraj Joshi",
    title: `Neeraj Joshi is the Chief Product Officer (CPO), leading product strategy and development. With 20 years in product management, Neeraj oversees product lifecycle, defines product roadmaps, and manages product teams. His role includes conducting market research, driving innovation, and ensuring products meet customer needs. Neeraj’s expertise in product development supports the company’s growth and product portfolio enhancement.`,
    address: "6465 Marigold St, Patna",
  },
  {
    id: 65,
    name: "Suman Sharma",
    title: `Suman Sharma serves as the Director of Strategic Planning, focusing on business strategy and growth. With 18 years in strategic management, Suman develops and implements strategic plans, manages growth projects, and analyzes market trends. Her role includes coordinating strategic initiatives, supporting business objectives, and driving long-term growth. Suman’s expertise in strategic planning supports the company’s competitive positioning and success.`,
    address: "6566 Tulip St, Bangalore",
  },
  {
    id: 66,
    name: "Rakesh Kumar",
    title: `Rakesh Kumar is the Chief Technology Officer (CTO), overseeing technology strategy and innovation. With 19 years in technology leadership, Rakesh manages IT projects, drives digital transformation, and ensures alignment with business goals. His role includes evaluating emerging technologies, improving systems, and leading technology initiatives. Rakesh’s expertise in technology management supports the company’s technological advancements and operational efficiency.`,
    address: "6667 Cedar St, Agra",
  },
  {
    id: 67,
    name: "Poonam Yadav",
    title: `Poonam Yadav is the Director of Human Resources, managing HR functions and employee relations. With over 16 years in HR management, Poonam develops HR strategies, manages recruitment, and oversees employee development. Her role includes improving employee engagement, handling conflict resolution, and ensuring compliance with labor laws. Poonam’s expertise in HR supports the company’s growth and workplace culture.`,
    address: "6768 Marigold St, Kanpur",
  },
  {
    id: 68,
    name: "Shivani Gupta",
    title: `Shivani Gupta is the Chief Compliance Officer (CCO), overseeing regulatory compliance and risk management. With 18 years in compliance, Shivani ensures adherence to laws and regulations. Her role includes managing compliance programs, conducting audits, and addressing regulatory issues. Shivani’s expertise in compliance supports the company’s ethical standards and regulatory adherence.`,
    address: "6869 Lotus St, Coimbatore",
  },
  {
    id: 69,
    name: "Amit Patel",
    title: `Amit Patel is the Director of Sales, focusing on driving sales performance and strategy. With over 17 years in sales management, Amit develops sales strategies, manages sales teams, and oversees client relationships. His role includes analyzing sales performance, identifying growth opportunities, and achieving sales targets. Amit’s expertise in sales supports the company’s revenue growth and market presence.`,
    address: "6970 Cedar St, Bhopal",
  },
  {
    id: 70,
    name: "Ravi Yadav",
    title: `Ravi Yadav is the Chief Operating Officer (COO), managing day-to-day operations and process improvements. With 20 years in operations management, Ravi oversees operational workflows, implements process changes, and enhances productivity. His role includes managing resources, ensuring smooth operations, and optimizing efficiency. Ravi’s expertise in operations supports the company’s operational goals and cost management.`,
    address: "7071 Tulip St, Surat",
  },
];
